
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "touch/src",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "touch/src/device/filesystem/HTML5.js",
  "Ext.device.purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.sqlite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.sqlite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "YourTour": "app",
  "YourTour.store.RouteMemberStore": "app/store/UserStore.js",
  "YourTour.store.UserStore": "app/store/RouteMemberStore.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [],
  "Ext.BingMap": [],
  "Ext.Button": [],
  "Ext.Component": [
    "Ext.lib.Component"
  ],
  "Ext.ComponentManager": [
    "Ext.ComponentMgr"
  ],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "Ext.lib.Container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [
    "Ext.EventedBase"
  ],
  "Ext.Img": [],
  "Ext.ItemCollection": [],
  "Ext.Label": [],
  "Ext.LoadMask": [],
  "Ext.Map": [],
  "Ext.Mask": [],
  "Ext.Media": [],
  "Ext.Menu": [],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "Ext.lib.Panel"
  ],
  "Ext.ProgressIndicator": [],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [],
  "Ext.Sheet": [],
  "Ext.Sortable": [],
  "Ext.Spacer": [],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [],
  "Ext.TitleBar": [],
  "Ext.Toast": [],
  "Ext.Toolbar": [],
  "Ext.Video": [],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "Ext.Carousel"
  ],
  "Ext.carousel.Indicator": [
    "Ext.Carousel.Indicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [],
  "Ext.data.JsonP": [
    "Ext.util.JSONP"
  ],
  "Ext.data.JsonStore": [],
  "Ext.data.Model": [
    "Ext.data.Record"
  ],
  "Ext.data.ModelManager": [
    "Ext.ModelMgr",
    "Ext.ModelManager"
  ],
  "Ext.data.NodeInterface": [
    "Ext.data.Node"
  ],
  "Ext.data.NodeStore": [],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [],
  "Ext.data.StoreManager": [
    "Ext.StoreMgr",
    "Ext.data.StoreMgr",
    "Ext.StoreManager"
  ],
  "Ext.data.TreeStore": [],
  "Ext.data.Types": [],
  "Ext.data.Validations": [
    "Ext.data.validations"
  ],
  "Ext.data.association.Association": [
    "Ext.data.Association"
  ],
  "Ext.data.association.BelongsTo": [
    "Ext.data.BelongsToAssociation"
  ],
  "Ext.data.association.HasMany": [
    "Ext.data.HasManyAssociation"
  ],
  "Ext.data.association.HasOne": [
    "Ext.data.HasOneAssociation"
  ],
  "Ext.data.identifier.Sequential": [],
  "Ext.data.identifier.Simple": [],
  "Ext.data.identifier.Uuid": [],
  "Ext.data.plugin.Buffered": [],
  "Ext.data.proxy.Ajax": [
    "Ext.data.HttpProxy",
    "Ext.data.AjaxProxy"
  ],
  "Ext.data.proxy.Client": [
    "Ext.proxy.ClientProxy"
  ],
  "Ext.data.proxy.Direct": [
    "Ext.data.DirectProxy"
  ],
  "Ext.data.proxy.JsonP": [
    "Ext.data.ScriptTagProxy"
  ],
  "Ext.data.proxy.LocalStorage": [
    "Ext.data.LocalStorageProxy"
  ],
  "Ext.data.proxy.Memory": [
    "Ext.data.MemoryProxy"
  ],
  "Ext.data.proxy.Proxy": [
    "Ext.data.DataProxy",
    "Ext.data.Proxy"
  ],
  "Ext.data.proxy.Rest": [
    "Ext.data.RestProxy"
  ],
  "Ext.data.proxy.Server": [
    "Ext.data.ServerProxy"
  ],
  "Ext.data.proxy.SessionStorage": [
    "Ext.data.SessionStorageProxy"
  ],
  "Ext.data.proxy.Sql": [
    "Ext.data.proxy.SQL"
  ],
  "Ext.data.proxy.WebStorage": [
    "Ext.data.WebStorageProxy"
  ],
  "Ext.data.reader.Array": [
    "Ext.data.ArrayReader"
  ],
  "Ext.data.reader.Json": [
    "Ext.data.JsonReader"
  ],
  "Ext.data.reader.Reader": [
    "Ext.data.Reader",
    "Ext.data.DataReader"
  ],
  "Ext.data.reader.Xml": [
    "Ext.data.XmlReader"
  ],
  "Ext.data.writer.Json": [
    "Ext.data.JsonWriter"
  ],
  "Ext.data.writer.Writer": [
    "Ext.data.DataWriter",
    "Ext.data.Writer"
  ],
  "Ext.data.writer.Xml": [
    "Ext.data.XmlWriter"
  ],
  "Ext.dataview.DataView": [
    "Ext.DataView"
  ],
  "Ext.dataview.IndexBar": [
    "Ext.IndexBar"
  ],
  "Ext.dataview.List": [
    "Ext.List"
  ],
  "Ext.dataview.ListItemHeader": [],
  "Ext.dataview.NestedList": [
    "Ext.NestedList"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [],
  "Ext.dataview.component.ListItem": [],
  "Ext.dataview.component.SimpleListItem": [],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [
    "Ext.device.accelerometer.PhoneGap"
  ],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [
    "Ext.device.camera.PhoneGap"
  ],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [
    "Ext.device.capture.Simulator"
  ],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [
    "Ext.device.compass.PhoneGap"
  ],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [
    "Ext.device.connection.PhoneGap"
  ],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [
    "Ext.device.contacts.PhoneGap"
  ],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [
    "Ext.device.device.PhoneGap"
  ],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [
    "Ext.device.filesystem.PhoneGap"
  ],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [
    "Ext.device.geolocation.PhoneGap"
  ],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [
    "Ext.device.globalization.PhoneGap"
  ],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [
    "Ext.device.media.PhoneGap"
  ],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [
    "Ext.device.notification.PhoneGap"
  ],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [
    "Ext.device.splashscreen.PhoneGap"
  ],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [
    "Ext.device.storage.PhoneGap"
  ],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [],
  "Ext.direct.ExceptionEvent": [],
  "Ext.direct.JsonProvider": [],
  "Ext.direct.Manager": [
    "Ext.Direct"
  ],
  "Ext.direct.PollingProvider": [],
  "Ext.direct.Provider": [],
  "Ext.direct.RemotingEvent": [],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [],
  "Ext.direct.Transaction": [
    "Ext.Direct.Transaction"
  ],
  "Ext.dom.CompositeElement": [
    "Ext.CompositeElement"
  ],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [
    "Ext.EventObject"
  ],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "Ext.form.Checkbox"
  ],
  "Ext.field.DatePicker": [
    "Ext.form.DatePicker"
  ],
  "Ext.field.DatePickerNative": [
    "Ext.form.DatePickerNative"
  ],
  "Ext.field.Email": [
    "Ext.form.Email"
  ],
  "Ext.field.Field": [
    "Ext.form.Field"
  ],
  "Ext.field.File": [],
  "Ext.field.FileInput": [],
  "Ext.field.Hidden": [
    "Ext.form.Hidden"
  ],
  "Ext.field.Input": [],
  "Ext.field.Number": [
    "Ext.form.Number"
  ],
  "Ext.field.Password": [
    "Ext.form.Password"
  ],
  "Ext.field.Radio": [
    "Ext.form.Radio"
  ],
  "Ext.field.Search": [
    "Ext.form.Search"
  ],
  "Ext.field.Select": [
    "Ext.form.Select"
  ],
  "Ext.field.Slider": [
    "Ext.form.Slider"
  ],
  "Ext.field.Spinner": [
    "Ext.form.Spinner"
  ],
  "Ext.field.Text": [
    "Ext.form.Text"
  ],
  "Ext.field.TextArea": [
    "Ext.form.TextArea"
  ],
  "Ext.field.TextAreaInput": [],
  "Ext.field.Toggle": [
    "Ext.form.Toggle"
  ],
  "Ext.field.Url": [
    "Ext.form.Url"
  ],
  "Ext.form.FieldSet": [],
  "Ext.form.Panel": [
    "Ext.form.FormPanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [],
  "Ext.fx.animation.Fade": [
    "Ext.fx.animation.FadeIn"
  ],
  "Ext.fx.animation.FadeOut": [],
  "Ext.fx.animation.Flip": [],
  "Ext.fx.animation.Pop": [
    "Ext.fx.animation.PopIn"
  ],
  "Ext.fx.animation.PopOut": [],
  "Ext.fx.animation.Slide": [
    "Ext.fx.animation.SlideIn"
  ],
  "Ext.fx.animation.SlideOut": [],
  "Ext.fx.animation.Wipe": [
    "Ext.fx.animation.WipeIn"
  ],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [],
  "Ext.fx.easing.EaseOut": [],
  "Ext.fx.easing.Linear": [],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [],
  "Ext.fx.layout.card.Cube": [],
  "Ext.fx.layout.card.Fade": [],
  "Ext.fx.layout.card.Flip": [],
  "Ext.fx.layout.card.Pop": [],
  "Ext.fx.layout.card.Reveal": [],
  "Ext.fx.layout.card.Scroll": [],
  "Ext.fx.layout.card.ScrollCover": [],
  "Ext.fx.layout.card.ScrollReveal": [],
  "Ext.fx.layout.card.Slide": [],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [],
  "Ext.layout.Card": [],
  "Ext.layout.Default": [],
  "Ext.layout.Fit": [],
  "Ext.layout.FlexBox": [],
  "Ext.layout.Float": [],
  "Ext.layout.HBox": [],
  "Ext.layout.VBox": [],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [
    "Ext.util.Observable"
  ],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "Ext.NavigationView"
  ],
  "Ext.picker.Date": [
    "Ext.DatePicker"
  ],
  "Ext.picker.Picker": [
    "Ext.Picker"
  ],
  "Ext.picker.Slot": [
    "Ext.Picker.Slot"
  ],
  "Ext.plugin.BufferedList": [],
  "Ext.plugin.ListPaging": [],
  "Ext.plugin.PullRefresh": [],
  "Ext.plugin.SortableList": [],
  "Ext.scroll.Indicator": [
    "Ext.util.Indicator"
  ],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [
    "Ext.util.ScrollView"
  ],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [],
  "Ext.slider.Thumb": [],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "Ext.TabBar"
  ],
  "Ext.tab.Panel": [
    "Ext.TabPanel"
  ],
  "Ext.tab.Tab": [
    "Ext.Tab"
  ],
  "Ext.table.Cell": [],
  "Ext.table.Row": [],
  "Ext.table.Table": [],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [
    "Ext.util.GeoLocation"
  ],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [
    "ParseHelper"
  ],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [],
  "Ext.ux.parse.Reader": [],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [],
  "Ext.ux.parse.association.Relation": [],
  "Ext.ux.picker.Time": [],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [
    "Ext.viewport.WP"
  ],
  "YourTour.controller.BaseCtrl": [],
  "YourTour.controller.CommonMainCtrl": [],
  "YourTour.controller.ExpertMainCtrl": [],
  "YourTour.controller.Launch": [],
  "YourTour.controller.LineMainCtrl": [],
  "YourTour.controller.MainCtrl": [],
  "YourTour.controller.MemberMainCtrl": [],
  "YourTour.controller.MessageMainCtrl": [],
  "YourTour.controller.PlaceMainCtrl": [],
  "YourTour.controller.PlaceSelectionCtrl": [],
  "YourTour.controller.ResourceMainCtrl": [],
  "YourTour.controller.ServiceMainCtrl": [],
  "YourTour.controller.SettingMainCtrl": [],
  "YourTour.controller.UserMainCtrl": [],
  "YourTour.controller.home.AlongMainCtrl": [],
  "YourTour.controller.home.BestMainCtrl": [],
  "YourTour.controller.home.HomeMainCtrl": [],
  "YourTour.controller.home.TalentMainCtrl": [],
  "YourTour.controller.route.RouteMainCtrl": [],
  "YourTour.controller.route.RouteScheduleListCtrl": [],
  "YourTour.controller.route.RouteSchedulePlanCtrl": [],
  "YourTour.controller.route.ScheduleDetailCtrl": [],
  "YourTour.controller.route.ScheduleListCtrl": [],
  "YourTour.controller.route.ScheduleReferenceCtrl": [],
  "YourTour.controller.user.AccountMainCtrl": [],
  "YourTour.controller.user.UserListCtrl": [],
  "YourTour.model.ActivityItemModel": [],
  "YourTour.model.AlongModel": [],
  "YourTour.model.BaseModel": [],
  "YourTour.model.BestModel": [],
  "YourTour.model.CacheModel": [],
  "YourTour.model.ChatModel": [],
  "YourTour.model.CommentModel": [],
  "YourTour.model.ExpertModel": [],
  "YourTour.model.HomeCarouselModel": [],
  "YourTour.model.HomeModel": [],
  "YourTour.model.LaunchModel": [],
  "YourTour.model.LineItemModel": [],
  "YourTour.model.LineModel": [],
  "YourTour.model.LiveModel": [],
  "YourTour.model.LocalCache": [],
  "YourTour.model.MessageContentModel": [],
  "YourTour.model.MessageSessionModel": [],
  "YourTour.model.OptionModel": [],
  "YourTour.model.PlaceModel": [],
  "YourTour.model.ResourceModel": [],
  "YourTour.model.RouteActivityModel": [],
  "YourTour.model.RouteModel": [],
  "YourTour.model.RouteScheduleModel": [],
  "YourTour.model.ServiceModel": [],
  "YourTour.model.TalentModel": [],
  "YourTour.model.UserModel": [],
  "YourTour.model.common.ResponseModel": [],
  "YourTour.store.AjaxStore": [],
  "YourTour.store.AlongListStore": [],
  "YourTour.store.BestListStore": [],
  "YourTour.store.CommentStore": [],
  "YourTour.store.DummyStore": [],
  "YourTour.store.HomeStore": [],
  "YourTour.store.LaunchStore": [],
  "YourTour.store.LineStore": [],
  "YourTour.store.LocalStore": [],
  "YourTour.store.MessageContentStore": [],
  "YourTour.store.MessageSessionStore": [],
  "YourTour.store.PlaceStore": [],
  "YourTour.store.ResourceFoodStore": [],
  "YourTour.store.ResourcePlayStore": [],
  "YourTour.store.ResourceStore": [],
  "YourTour.store.RouteMemberStore": [],
  "YourTour.store.RouteStore": [],
  "YourTour.store.SessionStore": [],
  "YourTour.store.TalentListStore": [],
  "YourTour.store.UserStore": [],
  "YourTour.util.Context": [],
  "YourTour.view.Launch": [],
  "YourTour.view.MainView": [],
  "YourTour.view.SearchMain": [],
  "YourTour.view.common.CarouselItem": [],
  "YourTour.view.common.CommentFormView": [],
  "YourTour.view.common.CommentListDataItem": [],
  "YourTour.view.common.CommentListView": [],
  "YourTour.view.common.ContentReadView": [],
  "YourTour.view.common.ExpertServiceFormView": [],
  "YourTour.view.common.ExpertServiceListDataItem": [],
  "YourTour.view.common.ExpertServiceListView": [],
  "YourTour.view.common.FieldEditView": [],
  "YourTour.view.common.MessageDataItemView": [],
  "YourTour.view.common.MessageGroupView": [],
  "YourTour.view.common.MessageMainView": [],
  "YourTour.view.common.PlaceGridItemView": [],
  "YourTour.view.common.TimeSelectionView": [],
  "YourTour.view.community.LiveMainView": [],
  "YourTour.view.expert.ExpertApplyView": [],
  "YourTour.view.expert.ExpertDataItem": [],
  "YourTour.view.expert.ExpertIntroFormView": [],
  "YourTour.view.expert.ExpertListView": [],
  "YourTour.view.expert.ExpertMainView": [],
  "YourTour.view.expert.ExpertRecommendDataItem": [],
  "YourTour.view.expert.ExpertRecommendIntroItem": [],
  "YourTour.view.expert.ExpertRecommendIntroView": [],
  "YourTour.view.expert.ExpertRecommendListView": [],
  "YourTour.view.expert.ExpertRouteDataItem": [],
  "YourTour.view.expert.ExpertServiceDataItem": [],
  "YourTour.view.expert.ExpertServiceEditView": [],
  "YourTour.view.home.AlongDetailView": [],
  "YourTour.view.home.AlongItemView": [],
  "YourTour.view.home.AlongListItemView": [],
  "YourTour.view.home.AlongListView": [],
  "YourTour.view.home.BestItemView": [],
  "YourTour.view.home.BestListItemView": [],
  "YourTour.view.home.BestListView": [],
  "YourTour.view.home.CarouselItemView": [],
  "YourTour.view.home.ChatItemView": [],
  "YourTour.view.home.HomeMain": [],
  "YourTour.view.home.HomeMainView": [],
  "YourTour.view.home.LiveItemView": [],
  "YourTour.view.home.TalentItemView": [],
  "YourTour.view.home.TalentListItemView": [],
  "YourTour.view.home.TalentListView": [],
  "YourTour.view.line.LineResourceItem": [],
  "YourTour.view.member.MemberAddView": [],
  "YourTour.view.member.MemberDataItem": [],
  "YourTour.view.member.MemberItemView": [],
  "YourTour.view.member.MemberMainView": [],
  "YourTour.view.member.MemberPositionView": [],
  "YourTour.view.member.MemberSearchView": [],
  "YourTour.view.place.PlaceExpertView": [],
  "YourTour.view.place.PlaceFoodView": [],
  "YourTour.view.place.PlaceMainView": [],
  "YourTour.view.place.PlaceOverviewView": [],
  "YourTour.view.place.PlaceSceneView": [],
  "YourTour.view.place.PlaceSelectionAbroadItem": [],
  "YourTour.view.place.PlaceSelectionDataItem": [],
  "YourTour.view.place.PlaceSelectionHomeItem": [],
  "YourTour.view.place.PlaceSelectionRecommendItem": [],
  "YourTour.view.place.PlaceSelectionTypeDataItem": [],
  "YourTour.view.place.PlaceSelectionView": [],
  "YourTour.view.resource.ResourceActivityItem": [],
  "YourTour.view.resource.ResourceActivityItemFormView": [],
  "YourTour.view.resource.ResourceActivityItemListView": [],
  "YourTour.view.resource.ResourceFoodDataItem": [],
  "YourTour.view.resource.ResourceFoodListView": [],
  "YourTour.view.resource.ResourceFormView": [],
  "YourTour.view.resource.ResourceMapView": [],
  "YourTour.view.resource.ResourcePlayDataItem": [],
  "YourTour.view.resource.ResourcePlayListView": [],
  "YourTour.view.resource.ResourceSceneView": [],
  "YourTour.view.resource.ResourceSelectionView": [],
  "YourTour.view.resource.ResourceView": [],
  "YourTour.view.route.RouteActivityEditView": [],
  "YourTour.view.route.RouteActivityItemDataItem": [],
  "YourTour.view.route.RouteImageView": [],
  "YourTour.view.route.RouteImpressionView": [],
  "YourTour.view.route.RouteMainItem": [],
  "YourTour.view.route.RouteMainView": [],
  "YourTour.view.route.RoutePlaceDataItem": [],
  "YourTour.view.route.RoutePlaceEditView": [],
  "YourTour.view.route.RouteProvisionEditView": [],
  "YourTour.view.route.RouteProvisionView": [],
  "YourTour.view.route.RouteRecommendDataItem": [],
  "YourTour.view.route.RouteRecommendIntroductionItem": [],
  "YourTour.view.route.RouteRecommendIntroductionView": [],
  "YourTour.view.route.RouteRecommendListView": [],
  "YourTour.view.route.RouteRecommendScheduleItem": [],
  "YourTour.view.route.RouteScheduleDataView": [],
  "YourTour.view.route.RouteScheduleEditView": [],
  "YourTour.view.route.RouteScheduleFormView": [],
  "YourTour.view.route.RouteScheduleListDataItem": [],
  "YourTour.view.route.RouteScheduleListView": [],
  "YourTour.view.route.RouteSchedulePlanDataItem": [],
  "YourTour.view.route.RouteSchedulePlanView": [],
  "YourTour.view.route.RouteScheduleReferenceListView": [],
  "YourTour.view.route.RouteScheduleView": [],
  "YourTour.view.route.RouteSettingItem": [],
  "YourTour.view.route.RouteSettingView": [],
  "YourTour.view.route.Schedule": [],
  "YourTour.view.setting.UserSettingView": [],
  "YourTour.view.user.LoginMainView": [],
  "YourTour.view.user.LoginView": [],
  "YourTour.view.user.RegisterAccountView": [],
  "YourTour.view.user.RegisterAuthView": [],
  "YourTour.view.user.RegisterProfileView": [],
  "YourTour.view.user.UserListItem": [],
  "YourTour.view.user.UserListView": [],
  "YourTour.view.user.UserMainView": [],
  "YourTour.view.user.UserProfileView": [],
  "YourTour.view.widget.MarkedLabel": [],
  "YourTour.view.widget.ToolButton": [],
  "YourTour.view.widget.XBack": [],
  "YourTour.view.widget.XButton": [],
  "YourTour.view.widget.XCalendar": [
    "YourTour.XCalendar"
  ],
  "YourTour.view.widget.XCalendarItem": [],
  "YourTour.view.widget.XCarousel": [],
  "YourTour.view.widget.XCheckbox": [],
  "YourTour.view.widget.XDataItem": [],
  "YourTour.view.widget.XDataView": [],
  "YourTour.view.widget.XField": [],
  "YourTour.view.widget.XGenderPicker": [],
  "YourTour.view.widget.XGridItem": [],
  "YourTour.view.widget.XGridView": [],
  "YourTour.view.widget.XHeaderBar": [],
  "YourTour.view.widget.XIcon": [],
  "YourTour.view.widget.XImage": [],
  "YourTour.view.widget.XImagePicker": [],
  "YourTour.view.widget.XLabel": [],
  "YourTour.view.widget.XMultiField": [],
  "YourTour.view.widget.XMultiLabel": [],
  "YourTour.view.widget.XNavigation": [],
  "YourTour.view.widget.XPage": [],
  "YourTour.view.widget.XPageBody": [],
  "YourTour.view.widget.XPanel": [],
  "YourTour.view.widget.XPicker": [],
  "YourTour.view.widget.XPickerField": [],
  "YourTour.view.widget.XPlainButton": [],
  "YourTour.view.widget.XProcessing": [],
  "YourTour.view.widget.XScore": [],
  "YourTour.view.widget.XSearchField": [],
  "YourTour.view.widget.XSelecion": [],
  "YourTour.view.widget.XShare": [],
  "YourTour.view.widget.XSpacer": [],
  "YourTour.view.widget.XTappable": [],
  "YourTour.view.widget.XTextArea": [],
  "YourTour.view.widget.XTextField": [],
  "YourTour.view.widget.XTimeField": [
    "Ext.form.TimePicker"
  ],
  "YourTour.view.widget.XTimePicker": [
    "Ext.TimePicker"
  ],
  "YourTour.view.widget.XTitleBar": [],
  "YourTour.view.widget.XToolbar": [],
  "YourTour.view.widget.XVerticalLine": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.AbstractComponent": [],
  "Ext.AbstractManager": [],
  "Ext.AbstractPlugin": [],
  "Ext.ActionSheet": [
    "widget.actionsheet"
  ],
  "Ext.Ajax": [],
  "Ext.Anim": [],
  "Ext.AnimationQueue": [],
  "Ext.Audio": [
    "widget.audio"
  ],
  "Ext.BingMap": [
    "widget.bingmap"
  ],
  "Ext.Button": [
    "widget.button"
  ],
  "Ext.Component": [
    "widget.component"
  ],
  "Ext.ComponentManager": [],
  "Ext.ComponentQuery": [],
  "Ext.Container": [
    "widget.container"
  ],
  "Ext.Decorator": [],
  "Ext.Evented": [],
  "Ext.Img": [
    "widget.image",
    "widget.img"
  ],
  "Ext.ItemCollection": [],
  "Ext.Label": [
    "widget.label"
  ],
  "Ext.LoadMask": [
    "widget.loadmask"
  ],
  "Ext.Map": [
    "widget.map"
  ],
  "Ext.Mask": [
    "widget.mask"
  ],
  "Ext.Media": [
    "widget.media"
  ],
  "Ext.Menu": [
    "widget.menu"
  ],
  "Ext.MessageBox": [],
  "Ext.Panel": [
    "widget.panel"
  ],
  "Ext.ProgressIndicator": [
    "widget.progressindicator"
  ],
  "Ext.Promise": [],
  "Ext.SegmentedButton": [
    "widget.segmentedbutton"
  ],
  "Ext.Sheet": [
    "widget.sheet"
  ],
  "Ext.Sortable": [],
  "Ext.Spacer": [
    "widget.spacer"
  ],
  "Ext.TaskQueue": [],
  "Ext.Template": [],
  "Ext.Title": [
    "widget.title"
  ],
  "Ext.TitleBar": [
    "widget.titlebar"
  ],
  "Ext.Toast": [],
  "Ext.Toolbar": [
    "widget.toolbar"
  ],
  "Ext.Video": [
    "widget.video"
  ],
  "Ext.XTemplate": [],
  "Ext.XTemplateCompiler": [],
  "Ext.XTemplateParser": [],
  "Ext.app.Action": [],
  "Ext.app.Application": [],
  "Ext.app.Controller": [],
  "Ext.app.History": [],
  "Ext.app.Profile": [],
  "Ext.app.Route": [],
  "Ext.app.Router": [],
  "Ext.behavior.Behavior": [],
  "Ext.behavior.Draggable": [],
  "Ext.behavior.Scrollable": [],
  "Ext.behavior.Translatable": [],
  "Ext.carousel.Carousel": [
    "widget.carousel"
  ],
  "Ext.carousel.Indicator": [
    "widget.carouselindicator"
  ],
  "Ext.carousel.Infinite": [],
  "Ext.carousel.Item": [],
  "Ext.data.ArrayStore": [
    "store.array"
  ],
  "Ext.data.Batch": [],
  "Ext.data.Connection": [],
  "Ext.data.DirectStore": [
    "store.direct"
  ],
  "Ext.data.Error": [],
  "Ext.data.Errors": [],
  "Ext.data.Field": [
    "data.field"
  ],
  "Ext.data.JsonP": [],
  "Ext.data.JsonStore": [
    "store.json"
  ],
  "Ext.data.Model": [],
  "Ext.data.ModelManager": [],
  "Ext.data.NodeInterface": [],
  "Ext.data.NodeStore": [
    "store.node"
  ],
  "Ext.data.Operation": [],
  "Ext.data.Request": [],
  "Ext.data.ResultSet": [],
  "Ext.data.SortTypes": [],
  "Ext.data.Store": [
    "store.store"
  ],
  "Ext.data.StoreManager": [],
  "Ext.data.TreeStore": [
    "store.tree"
  ],
  "Ext.data.Types": [],
  "Ext.data.Validations": [],
  "Ext.data.association.Association": [],
  "Ext.data.association.BelongsTo": [
    "association.belongsto"
  ],
  "Ext.data.association.HasMany": [
    "association.hasmany"
  ],
  "Ext.data.association.HasOne": [
    "association.hasone"
  ],
  "Ext.data.identifier.Sequential": [
    "data.identifier.sequential"
  ],
  "Ext.data.identifier.Simple": [
    "data.identifier.simple"
  ],
  "Ext.data.identifier.Uuid": [
    "data.identifier.uuid"
  ],
  "Ext.data.plugin.Buffered": [
    "plugin.storebuffered"
  ],
  "Ext.data.proxy.Ajax": [
    "proxy.ajax"
  ],
  "Ext.data.proxy.Client": [],
  "Ext.data.proxy.Direct": [
    "proxy.direct"
  ],
  "Ext.data.proxy.JsonP": [
    "proxy.jsonp",
    "proxy.scripttag"
  ],
  "Ext.data.proxy.LocalStorage": [
    "proxy.localstorage"
  ],
  "Ext.data.proxy.Memory": [
    "proxy.memory"
  ],
  "Ext.data.proxy.Proxy": [
    "proxy.proxy"
  ],
  "Ext.data.proxy.Rest": [
    "proxy.rest"
  ],
  "Ext.data.proxy.Server": [
    "proxy.server"
  ],
  "Ext.data.proxy.SessionStorage": [
    "proxy.sessionstorage"
  ],
  "Ext.data.proxy.Sql": [
    "proxy.sql"
  ],
  "Ext.data.proxy.WebStorage": [],
  "Ext.data.reader.Array": [
    "reader.array"
  ],
  "Ext.data.reader.Json": [
    "reader.json"
  ],
  "Ext.data.reader.Reader": [],
  "Ext.data.reader.Xml": [
    "reader.xml"
  ],
  "Ext.data.writer.Json": [
    "writer.json"
  ],
  "Ext.data.writer.Writer": [
    "writer.base"
  ],
  "Ext.data.writer.Xml": [
    "writer.xml"
  ],
  "Ext.dataview.DataView": [
    "widget.dataview"
  ],
  "Ext.dataview.IndexBar": [],
  "Ext.dataview.List": [
    "widget.list"
  ],
  "Ext.dataview.ListItemHeader": [
    "widget.listitemheader"
  ],
  "Ext.dataview.NestedList": [
    "widget.nestedlist"
  ],
  "Ext.dataview.component.Container": [],
  "Ext.dataview.component.DataItem": [
    "widget.dataitem"
  ],
  "Ext.dataview.component.ListItem": [
    "widget.listitem"
  ],
  "Ext.dataview.component.SimpleListItem": [
    "widget.simplelistitem"
  ],
  "Ext.dataview.element.Container": [],
  "Ext.dataview.element.List": [],
  "Ext.device.Accelerometer": [],
  "Ext.device.Browser": [],
  "Ext.device.Camera": [],
  "Ext.device.Capture": [],
  "Ext.device.Communicator": [],
  "Ext.device.Compass": [],
  "Ext.device.Connection": [],
  "Ext.device.Contacts": [],
  "Ext.device.Device": [],
  "Ext.device.FileSystem": [],
  "Ext.device.Geolocation": [],
  "Ext.device.Globalization": [],
  "Ext.device.Media": [],
  "Ext.device.Notification": [],
  "Ext.device.Orientation": [],
  "Ext.device.Purchases": [],
  "Ext.device.Purchases.Product": [],
  "Ext.device.Push": [],
  "Ext.device.SQLite": [],
  "Ext.device.Splashscreen": [],
  "Ext.device.Storage": [],
  "Ext.device.Tunnel": [],
  "Ext.device.accelerometer.Abstract": [],
  "Ext.device.accelerometer.Cordova": [],
  "Ext.device.accelerometer.Simulator": [],
  "Ext.device.browser.Abstract": [],
  "Ext.device.browser.Cordova": [],
  "Ext.device.browser.Simulator": [],
  "Ext.device.browser.Window": [],
  "Ext.device.camera.Abstract": [],
  "Ext.device.camera.Cordova": [],
  "Ext.device.camera.Sencha": [],
  "Ext.device.camera.Simulator": [],
  "Ext.device.capture.Abstract": [],
  "Ext.device.capture.Cordova": [],
  "Ext.device.communicator.Android": [],
  "Ext.device.communicator.Default": [],
  "Ext.device.compass.Abstract": [],
  "Ext.device.compass.Cordova": [],
  "Ext.device.compass.Simulator": [],
  "Ext.device.connection.Abstract": [],
  "Ext.device.connection.Cordova": [],
  "Ext.device.connection.Sencha": [],
  "Ext.device.connection.Simulator": [],
  "Ext.device.contacts.Abstract": [],
  "Ext.device.contacts.Cordova": [],
  "Ext.device.contacts.Sencha": [],
  "Ext.device.device.Abstract": [],
  "Ext.device.device.Cordova": [],
  "Ext.device.device.Sencha": [],
  "Ext.device.device.Simulator": [],
  "Ext.device.filesystem.Abstract": [],
  "Ext.device.filesystem.Chrome": [],
  "Ext.device.filesystem.Cordova": [],
  "Ext.device.filesystem.DirectoryEntry": [],
  "Ext.device.filesystem.Entry": [],
  "Ext.device.filesystem.FileEntry": [],
  "Ext.device.filesystem.FileSystem": [],
  "Ext.device.filesystem.HTML5": [],
  "Ext.device.filesystem.Sencha": [],
  "Ext.device.filesystem.Simulator": [],
  "Ext.device.geolocation.Abstract": [],
  "Ext.device.geolocation.Cordova": [],
  "Ext.device.geolocation.Sencha": [],
  "Ext.device.geolocation.Simulator": [],
  "Ext.device.globalization.Abstract": [],
  "Ext.device.globalization.Cordova": [],
  "Ext.device.globalization.Simulator": [],
  "Ext.device.media.Abstract": [],
  "Ext.device.media.Cordova": [],
  "Ext.device.notification.Abstract": [],
  "Ext.device.notification.Cordova": [],
  "Ext.device.notification.Sencha": [],
  "Ext.device.notification.Simulator": [],
  "Ext.device.orientation.Abstract": [],
  "Ext.device.orientation.HTML5": [],
  "Ext.device.orientation.Sencha": [],
  "Ext.device.purchases.Purchase": [],
  "Ext.device.purchases.Sencha": [],
  "Ext.device.push.Abstract": [],
  "Ext.device.push.Cordova": [],
  "Ext.device.push.Sencha": [],
  "Ext.device.splashscreen.Abstract": [],
  "Ext.device.splashscreen.Cordova": [],
  "Ext.device.splashscreen.Simulator": [],
  "Ext.device.sqlite.Database": [],
  "Ext.device.sqlite.SQLResultSet": [],
  "Ext.device.sqlite.SQLResultSetRowList": [],
  "Ext.device.sqlite.SQLTransaction": [],
  "Ext.device.sqlite.Sencha": [],
  "Ext.device.storage.Abstract": [],
  "Ext.device.storage.Cordova": [],
  "Ext.device.storage.HTML5.Database": [],
  "Ext.device.storage.HTML5.HTML5": [],
  "Ext.device.storage.HTML5.SQLStatement": [],
  "Ext.device.storage.Simulator": [],
  "Ext.device.tunnel.Abstract": [],
  "Ext.device.tunnel.Connection": [],
  "Ext.device.tunnel.Sencha": [],
  "Ext.device.tunnel.Simulator": [],
  "Ext.direct.Event": [
    "direct.event"
  ],
  "Ext.direct.ExceptionEvent": [
    "direct.exception"
  ],
  "Ext.direct.JsonProvider": [
    "direct.jsonprovider"
  ],
  "Ext.direct.Manager": [],
  "Ext.direct.PollingProvider": [
    "direct.pollingprovider"
  ],
  "Ext.direct.Provider": [
    "direct.provider"
  ],
  "Ext.direct.RemotingEvent": [
    "direct.rpc"
  ],
  "Ext.direct.RemotingMethod": [],
  "Ext.direct.RemotingProvider": [
    "direct.remotingprovider"
  ],
  "Ext.direct.Transaction": [
    "direct.transaction"
  ],
  "Ext.dom.CompositeElement": [],
  "Ext.event.Controller": [],
  "Ext.event.Dispatcher": [],
  "Ext.event.Dom": [],
  "Ext.event.Event": [],
  "Ext.event.ListenerStack": [],
  "Ext.event.Touch": [],
  "Ext.event.publisher.ComponentDelegation": [],
  "Ext.event.publisher.ComponentPaint": [],
  "Ext.event.publisher.ComponentSize": [],
  "Ext.event.publisher.Dom": [],
  "Ext.event.publisher.ElementPaint": [],
  "Ext.event.publisher.ElementSize": [],
  "Ext.event.publisher.Publisher": [],
  "Ext.event.publisher.TouchGesture": [],
  "Ext.event.recognizer.DoubleTap": [],
  "Ext.event.recognizer.Drag": [],
  "Ext.event.recognizer.EdgeSwipe": [],
  "Ext.event.recognizer.HorizontalSwipe": [],
  "Ext.event.recognizer.LongPress": [],
  "Ext.event.recognizer.MultiTouch": [],
  "Ext.event.recognizer.Pinch": [],
  "Ext.event.recognizer.Recognizer": [],
  "Ext.event.recognizer.Rotate": [],
  "Ext.event.recognizer.SingleTouch": [],
  "Ext.event.recognizer.Swipe": [],
  "Ext.event.recognizer.Tap": [],
  "Ext.event.recognizer.Touch": [],
  "Ext.event.recognizer.VerticalSwipe": [],
  "Ext.field.Checkbox": [
    "widget.checkboxfield"
  ],
  "Ext.field.DatePicker": [
    "widget.datepickerfield"
  ],
  "Ext.field.DatePickerNative": [
    "widget.datepickernativefield"
  ],
  "Ext.field.Email": [
    "widget.emailfield"
  ],
  "Ext.field.Field": [
    "widget.field"
  ],
  "Ext.field.File": [
    "widget.filefield"
  ],
  "Ext.field.FileInput": [
    "widget.fileinput"
  ],
  "Ext.field.Hidden": [
    "widget.hiddenfield"
  ],
  "Ext.field.Input": [
    "widget.input"
  ],
  "Ext.field.Number": [
    "widget.numberfield"
  ],
  "Ext.field.Password": [
    "widget.passwordfield"
  ],
  "Ext.field.Radio": [
    "widget.radiofield"
  ],
  "Ext.field.Search": [
    "widget.searchfield"
  ],
  "Ext.field.Select": [
    "widget.selectfield"
  ],
  "Ext.field.Slider": [
    "widget.sliderfield"
  ],
  "Ext.field.Spinner": [
    "widget.spinnerfield"
  ],
  "Ext.field.Text": [
    "widget.textfield"
  ],
  "Ext.field.TextArea": [
    "widget.textareafield"
  ],
  "Ext.field.TextAreaInput": [
    "widget.textareainput"
  ],
  "Ext.field.Toggle": [
    "widget.togglefield"
  ],
  "Ext.field.Url": [
    "widget.urlfield"
  ],
  "Ext.form.FieldSet": [
    "widget.fieldset"
  ],
  "Ext.form.Panel": [
    "widget.formpanel"
  ],
  "Ext.fx.Animation": [],
  "Ext.fx.Easing": [],
  "Ext.fx.Runner": [],
  "Ext.fx.State": [],
  "Ext.fx.animation.Abstract": [],
  "Ext.fx.animation.Cube": [
    "animation.cube"
  ],
  "Ext.fx.animation.Fade": [
    "animation.fade",
    "animation.fadeIn"
  ],
  "Ext.fx.animation.FadeOut": [
    "animation.fadeOut"
  ],
  "Ext.fx.animation.Flip": [
    "animation.flip"
  ],
  "Ext.fx.animation.Pop": [
    "animation.pop",
    "animation.popIn"
  ],
  "Ext.fx.animation.PopOut": [
    "animation.popOut"
  ],
  "Ext.fx.animation.Slide": [
    "animation.slide",
    "animation.slideIn"
  ],
  "Ext.fx.animation.SlideOut": [
    "animation.slideOut"
  ],
  "Ext.fx.animation.Wipe": [],
  "Ext.fx.animation.WipeOut": [],
  "Ext.fx.easing.Abstract": [],
  "Ext.fx.easing.Bounce": [],
  "Ext.fx.easing.BoundMomentum": [],
  "Ext.fx.easing.EaseIn": [
    "easing.ease-in"
  ],
  "Ext.fx.easing.EaseOut": [
    "easing.ease-out"
  ],
  "Ext.fx.easing.Linear": [
    "easing.linear"
  ],
  "Ext.fx.easing.Momentum": [],
  "Ext.fx.layout.Card": [],
  "Ext.fx.layout.card.Abstract": [],
  "Ext.fx.layout.card.Cover": [
    "fx.layout.card.cover"
  ],
  "Ext.fx.layout.card.Cube": [
    "fx.layout.card.cube"
  ],
  "Ext.fx.layout.card.Fade": [
    "fx.layout.card.fade"
  ],
  "Ext.fx.layout.card.Flip": [
    "fx.layout.card.flip"
  ],
  "Ext.fx.layout.card.Pop": [
    "fx.layout.card.pop"
  ],
  "Ext.fx.layout.card.Reveal": [
    "fx.layout.card.reveal"
  ],
  "Ext.fx.layout.card.Scroll": [
    "fx.layout.card.scroll"
  ],
  "Ext.fx.layout.card.ScrollCover": [
    "fx.layout.card.scrollcover"
  ],
  "Ext.fx.layout.card.ScrollReveal": [
    "fx.layout.card.scrollreveal"
  ],
  "Ext.fx.layout.card.Slide": [
    "fx.layout.card.slide"
  ],
  "Ext.fx.layout.card.Style": [],
  "Ext.fx.runner.Css": [],
  "Ext.fx.runner.CssAnimation": [],
  "Ext.fx.runner.CssTransition": [],
  "Ext.layout.Abstract": [],
  "Ext.layout.Box": [
    "layout.tablebox"
  ],
  "Ext.layout.Card": [
    "layout.card"
  ],
  "Ext.layout.Default": [
    "layout.auto",
    "layout.default"
  ],
  "Ext.layout.Fit": [
    "layout.fit"
  ],
  "Ext.layout.FlexBox": [
    "layout.box"
  ],
  "Ext.layout.Float": [
    "layout.float"
  ],
  "Ext.layout.HBox": [
    "layout.hbox"
  ],
  "Ext.layout.VBox": [
    "layout.vbox"
  ],
  "Ext.layout.wrapper.BoxDock": [],
  "Ext.layout.wrapper.Dock": [],
  "Ext.layout.wrapper.Inner": [],
  "Ext.mixin.Bindable": [],
  "Ext.mixin.Filterable": [],
  "Ext.mixin.Mixin": [],
  "Ext.mixin.Observable": [],
  "Ext.mixin.Progressable": [],
  "Ext.mixin.Selectable": [],
  "Ext.mixin.Sortable": [],
  "Ext.mixin.Templatable": [],
  "Ext.mixin.Traversable": [],
  "Ext.navigation.Bar": [],
  "Ext.navigation.View": [
    "widget.navigationview"
  ],
  "Ext.picker.Date": [
    "widget.datepicker"
  ],
  "Ext.picker.Picker": [
    "widget.picker"
  ],
  "Ext.picker.Slot": [
    "widget.pickerslot"
  ],
  "Ext.plugin.BufferedList": [
    "plugin.bufferedlist"
  ],
  "Ext.plugin.ListPaging": [
    "plugin.listpaging"
  ],
  "Ext.plugin.PullRefresh": [
    "plugin.pullrefresh"
  ],
  "Ext.plugin.SortableList": [
    "plugin.sortablelist"
  ],
  "Ext.scroll.Indicator": [],
  "Ext.scroll.Scroller": [],
  "Ext.scroll.View": [],
  "Ext.scroll.indicator.Abstract": [],
  "Ext.scroll.indicator.CssTransform": [],
  "Ext.scroll.indicator.Rounded": [],
  "Ext.scroll.indicator.ScrollPosition": [],
  "Ext.slider.Slider": [
    "widget.slider"
  ],
  "Ext.slider.Thumb": [
    "widget.thumb"
  ],
  "Ext.slider.Toggle": [],
  "Ext.tab.Bar": [
    "widget.tabbar"
  ],
  "Ext.tab.Panel": [
    "widget.tabpanel"
  ],
  "Ext.tab.Tab": [
    "widget.tab"
  ],
  "Ext.table.Cell": [
    "widget.tablecell"
  ],
  "Ext.table.Row": [
    "widget.tablerow"
  ],
  "Ext.table.Table": [
    "widget.table"
  ],
  "Ext.util.AbstractMixedCollection": [],
  "Ext.util.Audio": [],
  "Ext.util.BufferedCollection": [],
  "Ext.util.Collection": [],
  "Ext.util.DelayedTask": [],
  "Ext.util.Draggable": [],
  "Ext.util.Droppable": [],
  "Ext.util.Filter": [],
  "Ext.util.Format": [],
  "Ext.util.Geolocation": [],
  "Ext.util.Grouper": [],
  "Ext.util.HashMap": [],
  "Ext.util.Inflector": [],
  "Ext.util.InputBlocker": [],
  "Ext.util.LineSegment": [],
  "Ext.util.MixedCollection": [],
  "Ext.util.Offset": [],
  "Ext.util.PaintMonitor": [],
  "Ext.util.Point": [],
  "Ext.util.PositionMap": [],
  "Ext.util.Region": [],
  "Ext.util.SizeMonitor": [],
  "Ext.util.Sortable": [],
  "Ext.util.Sorter": [],
  "Ext.util.TapRepeater": [],
  "Ext.util.Translatable": [],
  "Ext.util.TranslatableGroup": [],
  "Ext.util.TranslatableList": [],
  "Ext.util.Wrapper": [],
  "Ext.util.paintmonitor.Abstract": [],
  "Ext.util.paintmonitor.CssAnimation": [],
  "Ext.util.paintmonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Abstract": [],
  "Ext.util.sizemonitor.Default": [],
  "Ext.util.sizemonitor.OverflowChange": [],
  "Ext.util.sizemonitor.Scroll": [],
  "Ext.util.translatable.Abstract": [],
  "Ext.util.translatable.CssPosition": [],
  "Ext.util.translatable.CssTransform": [],
  "Ext.util.translatable.Dom": [],
  "Ext.util.translatable.ScrollPosition": [],
  "Ext.ux.ActionOverFlowMenuButton": [],
  "Ext.ux.ApplicationMenu": [],
  "Ext.ux.ContextMenu": [],
  "Ext.ux.MenuButton": [],
  "Ext.ux.TabMenuButton": [],
  "Ext.ux.device.Analytics": [],
  "Ext.ux.device.Twitter": [],
  "Ext.ux.device.analytics.Abstract": [],
  "Ext.ux.device.analytics.Cordova": [],
  "Ext.ux.device.twitter.Abstract": [],
  "Ext.ux.device.twitter.Cordova": [],
  "Ext.ux.parse.Helper": [],
  "Ext.ux.parse.Model": [],
  "Ext.ux.parse.Proxy": [
    "proxy.parse"
  ],
  "Ext.ux.parse.Reader": [
    "reader.parse"
  ],
  "Ext.ux.parse.Store": [],
  "Ext.ux.parse.association.Pointer": [
    "association.pointer"
  ],
  "Ext.ux.parse.association.Relation": [
    "association.relation"
  ],
  "Ext.ux.picker.Time": [
    "widget.timepicker"
  ],
  "Ext.viewport.Android": [],
  "Ext.viewport.Default": [
    "widget.viewport"
  ],
  "Ext.viewport.Ios": [],
  "Ext.viewport.Viewport": [],
  "Ext.viewport.WindowsPhone": [],
  "YourTour.controller.BaseCtrl": [],
  "YourTour.controller.CommonMainCtrl": [],
  "YourTour.controller.ExpertMainCtrl": [],
  "YourTour.controller.Launch": [],
  "YourTour.controller.LineMainCtrl": [],
  "YourTour.controller.MainCtrl": [],
  "YourTour.controller.MemberMainCtrl": [],
  "YourTour.controller.MessageMainCtrl": [],
  "YourTour.controller.PlaceMainCtrl": [],
  "YourTour.controller.PlaceSelectionCtrl": [],
  "YourTour.controller.ResourceMainCtrl": [],
  "YourTour.controller.ServiceMainCtrl": [],
  "YourTour.controller.SettingMainCtrl": [],
  "YourTour.controller.UserMainCtrl": [],
  "YourTour.controller.home.AlongMainCtrl": [],
  "YourTour.controller.home.BestMainCtrl": [],
  "YourTour.controller.home.HomeMainCtrl": [],
  "YourTour.controller.home.TalentMainCtrl": [],
  "YourTour.controller.route.RouteMainCtrl": [],
  "YourTour.controller.route.RouteScheduleListCtrl": [],
  "YourTour.controller.route.RouteSchedulePlanCtrl": [],
  "YourTour.controller.route.ScheduleDetailCtrl": [],
  "YourTour.controller.route.ScheduleListCtrl": [],
  "YourTour.controller.route.ScheduleReferenceCtrl": [],
  "YourTour.controller.user.AccountMainCtrl": [],
  "YourTour.controller.user.UserListCtrl": [],
  "YourTour.model.ActivityItemModel": [],
  "YourTour.model.AlongModel": [],
  "YourTour.model.BaseModel": [],
  "YourTour.model.BestModel": [],
  "YourTour.model.CacheModel": [],
  "YourTour.model.ChatModel": [],
  "YourTour.model.CommentModel": [],
  "YourTour.model.ExpertModel": [],
  "YourTour.model.HomeCarouselModel": [],
  "YourTour.model.HomeModel": [],
  "YourTour.model.LaunchModel": [],
  "YourTour.model.LineItemModel": [],
  "YourTour.model.LineModel": [],
  "YourTour.model.LiveModel": [],
  "YourTour.model.LocalCache": [
    "widget.localCache"
  ],
  "YourTour.model.MessageContentModel": [],
  "YourTour.model.MessageSessionModel": [],
  "YourTour.model.OptionModel": [],
  "YourTour.model.PlaceModel": [],
  "YourTour.model.ResourceModel": [],
  "YourTour.model.RouteActivityModel": [],
  "YourTour.model.RouteModel": [],
  "YourTour.model.RouteScheduleModel": [],
  "YourTour.model.ServiceModel": [],
  "YourTour.model.TalentModel": [],
  "YourTour.model.UserModel": [],
  "YourTour.model.common.ResponseModel": [],
  "YourTour.store.AjaxStore": [],
  "YourTour.store.AlongListStore": [],
  "YourTour.store.BestListStore": [],
  "YourTour.store.CommentStore": [],
  "YourTour.store.DummyStore": [],
  "YourTour.store.HomeStore": [],
  "YourTour.store.LaunchStore": [],
  "YourTour.store.LineStore": [],
  "YourTour.store.LocalStore": [],
  "YourTour.store.MessageContentStore": [],
  "YourTour.store.MessageSessionStore": [],
  "YourTour.store.PlaceStore": [],
  "YourTour.store.ResourceFoodStore": [],
  "YourTour.store.ResourcePlayStore": [],
  "YourTour.store.ResourceStore": [],
  "YourTour.store.RouteMemberStore": [],
  "YourTour.store.RouteStore": [],
  "YourTour.store.SessionStore": [],
  "YourTour.store.TalentListStore": [],
  "YourTour.store.UserStore": [],
  "YourTour.util.Context": [
    "Context"
  ],
  "YourTour.view.Launch": [
    "widget.launch"
  ],
  "YourTour.view.MainView": [
    "widget.MainView"
  ],
  "YourTour.view.SearchMain": [
    "widget.searchmain"
  ],
  "YourTour.view.common.CarouselItem": [],
  "YourTour.view.common.CommentFormView": [],
  "YourTour.view.common.CommentListDataItem": [
    "widget.CommentListDataItem"
  ],
  "YourTour.view.common.CommentListView": [],
  "YourTour.view.common.ContentReadView": [],
  "YourTour.view.common.ExpertServiceFormView": [],
  "YourTour.view.common.ExpertServiceListDataItem": [
    "widget.ExpertServiceListDataItem"
  ],
  "YourTour.view.common.ExpertServiceListView": [],
  "YourTour.view.common.FieldEditView": [],
  "YourTour.view.common.MessageDataItemView": [
    "widget.MessageDataItemView"
  ],
  "YourTour.view.common.MessageGroupView": [],
  "YourTour.view.common.MessageMainView": [
    "widget.MessageMainView"
  ],
  "YourTour.view.common.PlaceGridItemView": [
    "widget.PlaceGridItemView"
  ],
  "YourTour.view.common.TimeSelectionView": [],
  "YourTour.view.community.LiveMainView": [
    "widget.LiveMainView"
  ],
  "YourTour.view.expert.ExpertApplyView": [
    "widget.ExpertApplyView"
  ],
  "YourTour.view.expert.ExpertDataItem": [
    "widget.ExpertDataItem"
  ],
  "YourTour.view.expert.ExpertIntroFormView": [],
  "YourTour.view.expert.ExpertListView": [
    "widget.ExpertListView"
  ],
  "YourTour.view.expert.ExpertMainView": [
    "widget.ExpertMainView"
  ],
  "YourTour.view.expert.ExpertRecommendDataItem": [
    "widget.ExpertRecommendDataItem"
  ],
  "YourTour.view.expert.ExpertRecommendIntroItem": [
    "widget.ExpertRecommendIntroItem"
  ],
  "YourTour.view.expert.ExpertRecommendIntroView": [],
  "YourTour.view.expert.ExpertRecommendListView": [],
  "YourTour.view.expert.ExpertRouteDataItem": [
    "widget.ExpertRouteDataItem"
  ],
  "YourTour.view.expert.ExpertServiceDataItem": [
    "widget.ExpertServiceDataItem"
  ],
  "YourTour.view.expert.ExpertServiceEditView": [],
  "YourTour.view.home.AlongDetailView": [],
  "YourTour.view.home.AlongItemView": [
    "widget.AlongItemView"
  ],
  "YourTour.view.home.AlongListItemView": [
    "widget.AlongListItemView"
  ],
  "YourTour.view.home.AlongListView": [
    "widget.AlongListView"
  ],
  "YourTour.view.home.BestItemView": [
    "widget.BestItemView"
  ],
  "YourTour.view.home.BestListItemView": [
    "widget.BestListItemView"
  ],
  "YourTour.view.home.BestListView": [
    "widget.BestListView"
  ],
  "YourTour.view.home.CarouselItemView": [
    "widget.CarouselItemView"
  ],
  "YourTour.view.home.ChatItemView": [
    "widget.ChatItemView"
  ],
  "YourTour.view.home.HomeMain": [
    "widget.HomeMain"
  ],
  "YourTour.view.home.HomeMainView": [
    "widget.HomeMainView"
  ],
  "YourTour.view.home.LiveItemView": [
    "widget.LiveItemView"
  ],
  "YourTour.view.home.TalentItemView": [
    "widget.TalentItemView"
  ],
  "YourTour.view.home.TalentListItemView": [
    "widget.TalentListItemView"
  ],
  "YourTour.view.home.TalentListView": [
    "widget.TalentListView"
  ],
  "YourTour.view.line.LineResourceItem": [
    "widget.LineResourceItem"
  ],
  "YourTour.view.member.MemberAddView": [
    "widget.MemberAddView"
  ],
  "YourTour.view.member.MemberDataItem": [
    "widget.MemberDataItem"
  ],
  "YourTour.view.member.MemberItemView": [
    "widget.MemberItemView"
  ],
  "YourTour.view.member.MemberMainView": [],
  "YourTour.view.member.MemberPositionView": [
    "widget.MemberPositionView"
  ],
  "YourTour.view.member.MemberSearchView": [],
  "YourTour.view.place.PlaceExpertView": [
    "widget.PlaceExpertView"
  ],
  "YourTour.view.place.PlaceFoodView": [
    "widget.PlaceFoodView"
  ],
  "YourTour.view.place.PlaceMainView": [
    "widget.PlaceMainView"
  ],
  "YourTour.view.place.PlaceOverviewView": [
    "widget.PlaceOverviewView"
  ],
  "YourTour.view.place.PlaceSceneView": [
    "widget.PlaceSceneView"
  ],
  "YourTour.view.place.PlaceSelectionAbroadItem": [
    "widget.PlaceSelectionAbroadItem"
  ],
  "YourTour.view.place.PlaceSelectionDataItem": [
    "widget.PlaceSelectionDataItem"
  ],
  "YourTour.view.place.PlaceSelectionHomeItem": [
    "widget.PlaceSelectionHomeItem"
  ],
  "YourTour.view.place.PlaceSelectionRecommendItem": [
    "widget.PlaceSelectionRecommendItem"
  ],
  "YourTour.view.place.PlaceSelectionTypeDataItem": [
    "widget.PlaceSelectionTypeDataItem"
  ],
  "YourTour.view.place.PlaceSelectionView": [],
  "YourTour.view.resource.ResourceActivityItem": [
    "widget.ResourceActivityItem"
  ],
  "YourTour.view.resource.ResourceActivityItemFormView": [
    "widget.ResourceActivityItemFormView"
  ],
  "YourTour.view.resource.ResourceActivityItemListView": [
    "widget.ResourceActivityItemListView"
  ],
  "YourTour.view.resource.ResourceFoodDataItem": [
    "widget.ResourceFoodDataItem"
  ],
  "YourTour.view.resource.ResourceFoodListView": [
    "widget.ResourceFoodListView"
  ],
  "YourTour.view.resource.ResourceFormView": [],
  "YourTour.view.resource.ResourceMapView": [
    "widget.ResourceMapView"
  ],
  "YourTour.view.resource.ResourcePlayDataItem": [
    "widget.ResourcePlayDataItem"
  ],
  "YourTour.view.resource.ResourcePlayListView": [
    "widget.ResourcePlayListView"
  ],
  "YourTour.view.resource.ResourceSceneView": [],
  "YourTour.view.resource.ResourceSelectionView": [
    "widget.SelectionListView"
  ],
  "YourTour.view.resource.ResourceView": [],
  "YourTour.view.route.RouteActivityEditView": [],
  "YourTour.view.route.RouteActivityItemDataItem": [
    "widget.RouteActivityItemDataItem"
  ],
  "YourTour.view.route.RouteImageView": [],
  "YourTour.view.route.RouteImpressionView": [],
  "YourTour.view.route.RouteMainItem": [
    "widget.RouteMainItem"
  ],
  "YourTour.view.route.RouteMainView": [
    "widget.RouteMainView"
  ],
  "YourTour.view.route.RoutePlaceDataItem": [
    "widget.RoutePlaceDataItem"
  ],
  "YourTour.view.route.RoutePlaceEditView": [],
  "YourTour.view.route.RouteProvisionEditView": [],
  "YourTour.view.route.RouteProvisionView": [],
  "YourTour.view.route.RouteRecommendDataItem": [
    "widget.RouteRecommendDataItem"
  ],
  "YourTour.view.route.RouteRecommendIntroductionItem": [
    "widget.RouteRecommendIntroductionItem"
  ],
  "YourTour.view.route.RouteRecommendIntroductionView": [],
  "YourTour.view.route.RouteRecommendListView": [],
  "YourTour.view.route.RouteRecommendScheduleItem": [
    "widget.RouteRecommendScheduleItem"
  ],
  "YourTour.view.route.RouteScheduleDataView": [
    "widget.RouteScheduleDataView"
  ],
  "YourTour.view.route.RouteScheduleEditView": [],
  "YourTour.view.route.RouteScheduleFormView": [],
  "YourTour.view.route.RouteScheduleListDataItem": [
    "widget.RouteScheduleListDataItem"
  ],
  "YourTour.view.route.RouteScheduleListView": [],
  "YourTour.view.route.RouteSchedulePlanDataItem": [
    "widget.RouteSchedulePlanDataItem"
  ],
  "YourTour.view.route.RouteSchedulePlanView": [],
  "YourTour.view.route.RouteScheduleReferenceListView": [],
  "YourTour.view.route.RouteScheduleView": [],
  "YourTour.view.route.RouteSettingItem": [
    "widget.RouteSettingItem"
  ],
  "YourTour.view.route.RouteSettingView": [],
  "YourTour.view.route.Schedule": [
    "widget.routenew"
  ],
  "YourTour.view.setting.UserSettingView": [
    "widget.UserSettingView"
  ],
  "YourTour.view.user.LoginMainView": [],
  "YourTour.view.user.LoginView": [
    "widget.LoginView"
  ],
  "YourTour.view.user.RegisterAccountView": [
    "widget.RegisterAccountView"
  ],
  "YourTour.view.user.RegisterAuthView": [
    "widget.RegisterAuthView"
  ],
  "YourTour.view.user.RegisterProfileView": [
    "widget.RegisterProfileView"
  ],
  "YourTour.view.user.UserListItem": [
    "widget.UserListItem"
  ],
  "YourTour.view.user.UserListView": [
    "widget.UserListView"
  ],
  "YourTour.view.user.UserMainView": [
    "widget.UserMainView"
  ],
  "YourTour.view.user.UserProfileView": [
    "widget.UserProfileView"
  ],
  "YourTour.view.widget.MarkedLabel": [
    "widget.markedlabel"
  ],
  "YourTour.view.widget.ToolButton": [
    "widget.toolbutton"
  ],
  "YourTour.view.widget.XBack": [
    "widget.xback"
  ],
  "YourTour.view.widget.XButton": [
    "widget.xbutton"
  ],
  "YourTour.view.widget.XCalendar": [
    "widget.xcalendar"
  ],
  "YourTour.view.widget.XCalendarItem": [
    "widget.xcalendaritem"
  ],
  "YourTour.view.widget.XCarousel": [
    "widget.xcarousel"
  ],
  "YourTour.view.widget.XCheckbox": [
    "widget.xcheckbox"
  ],
  "YourTour.view.widget.XDataItem": [],
  "YourTour.view.widget.XDataView": [
    "widget.xdataview"
  ],
  "YourTour.view.widget.XField": [
    "widget.xfield"
  ],
  "YourTour.view.widget.XGenderPicker": [
    "widget.xgenderpicker"
  ],
  "YourTour.view.widget.XGridItem": [],
  "YourTour.view.widget.XGridView": [
    "widget.xgridview"
  ],
  "YourTour.view.widget.XHeaderBar": [
    "widget.xheaderbar"
  ],
  "YourTour.view.widget.XIcon": [
    "widget.xicon"
  ],
  "YourTour.view.widget.XImage": [
    "widget.ximage"
  ],
  "YourTour.view.widget.XImagePicker": [
    "widget.ximagepicker"
  ],
  "YourTour.view.widget.XLabel": [
    "widget.xlabel"
  ],
  "YourTour.view.widget.XMultiField": [
    "widget.xmultifield"
  ],
  "YourTour.view.widget.XMultiLabel": [
    "widget.xmultilabel"
  ],
  "YourTour.view.widget.XNavigation": [
    "widget.xnavigation"
  ],
  "YourTour.view.widget.XPage": [
    "widget.xpage"
  ],
  "YourTour.view.widget.XPageBody": [
    "widget.xpagebody"
  ],
  "YourTour.view.widget.XPanel": [
    "widget.xpanel"
  ],
  "YourTour.view.widget.XPicker": [
    "widget.xpicker"
  ],
  "YourTour.view.widget.XPickerField": [
    "widget.xpickerfield"
  ],
  "YourTour.view.widget.XPlainButton": [
    "widget.xplainbutton"
  ],
  "YourTour.view.widget.XProcessing": [
    "widget.xprocessing"
  ],
  "YourTour.view.widget.XScore": [
    "widget.xscore"
  ],
  "YourTour.view.widget.XSearchField": [
    "widget.xsearchfield"
  ],
  "YourTour.view.widget.XSelecion": [],
  "YourTour.view.widget.XShare": [
    "widget.xshare"
  ],
  "YourTour.view.widget.XSpacer": [
    "widget.xspacer"
  ],
  "YourTour.view.widget.XTappable": [],
  "YourTour.view.widget.XTextArea": [
    "widget.xtextarea"
  ],
  "YourTour.view.widget.XTextField": [
    "widget.xtextfield"
  ],
  "YourTour.view.widget.XTimeField": [
    "widget.timepickerfield"
  ],
  "YourTour.view.widget.XTimePicker": [
    "widget.timepicker"
  ],
  "YourTour.view.widget.XTitleBar": [
    "widget.xtitlebar"
  ],
  "YourTour.view.widget.XToolbar": [
    "widget.xtoolbar"
  ],
  "YourTour.view.widget.XVerticalLine": [
    "widget.xvline"
  ]
});
